---
- apt_key:
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
- apt_repository:
    repo: 'deb http://packages.erlang-solutions.com/ubuntu {{ansible_lsb.codename}} contrib'
    state: present
- apt: update_cache=yes
- apt: name={{ item }} state=present
  with_items:
    - git
    - build-essential
- apt: name=erlang={{ erlang_version }} state=present
  register: erlang
- git: repo=git://github.com/elixir-lang/elixir.git
       dest=/tmp/elixir
       version={{ elixir_version }}
       accept_hostkey=true
  register: elixir
- shell: make clean install chdir=/tmp/elixir
  when: erlang.changed or elixir.changed
