---
- apt_repository:
    repo: 'deb http://packages.erlang-solutions.com/ubuntu {{ansible_lsb.codename}} contrib'
    state: present
- apt_key:
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
- apt: update_cache=yes
- apt: name=elixir state=present
